apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: harvester
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mount-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: harvester
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-mount-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-volumes
spec:
  selector:
    matchLabels:
      app: test-volumes
  template:
    metadata:
      labels:
        app: test-volumes
    spec:
      containers:
        - image: ubuntu:xenial
          name: myapp
          command: [ "/bin/sh", "-c" ]
          args: [ "tail -f /dev/null" ]
          volumeMounts:
            - mountPath: "/mnt-harvester"
              name: mount
#            - mountPath: "/mnt-longhorn"
#              name: longhorn-mount
          volumeDevices:
            - name: block
              devicePath: /dev/xvda
      volumes:
        - name: mount
          persistentVolumeClaim:
            claimName: mount-pvc
#        - name: longhorn-mount
#          persistentVolumeClaim:
#            claimName: longhorn-mount-pvc
        - name: block
          persistentVolumeClaim:
            claimName: block-pvc
